project:
  type: website
  output-dir: docs
website:
  title: "CS 5805"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: cosmo
    css: styles.css



